### ISSUE TITLE
If you `move` more than ones Stockfish gets confused the turn of the player

### ISSUE THREAD

**Issue by amanjpro** [agausmann/perftree#3]
Imagine this case:

```
$ perfttree my_movegen
fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
depth 5
move e2e4
move e7e5
move d2d4
diff
```

In the above case, Stockfish's output should consider that it is black's turn, not white, but what I get is possible moves of white! Not sure if this is a Stockfish problem (I doubt it), or perfttree's

**Comment by agausmann** [comment]
You have a couple of problems with your sample case. First is that the 8th rank in the FEN is missing a piece (I'd guess it's a black rook), and e5e7 is not a valid move for Black (although e7e5 is).

It works fine for me when I correct those things.

**Comment by amanjpro** [comment]
Oh, sorry they were copy-pasta problems. That is interesting. It didnt' work for me.

Does it matter that my commands were entered in a different order. Lemme paste a real example:

**Comment by amanjpro** [comment]
I cannot reproduce, sorry for the false alarm.

But I want to thank you a lot for this awesome tool!
