### ISSUE TITLE
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by movitzaaron** [agausmann/perftree#8]
Hey, I am really excited to try this to get the final few bugs out of my engine. However, whatever I pass in as the <script> it throws the error:
`Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`.
I have tried to pass .sh files, as well as a plethora of other files and file types to no success.

For example, I run
`perftree ./script.sh`
and get
`Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

but, running just ./script works fine and gives the correct output.
Thanks

**Comment by agausmann** [comment]
Do you have Stockfish installed? Does it run if you type `stockfish` in the terminal?

**Comment by movitzaaron** [comment]
Stockfish was installed but did not work on either `perftree` or `stockfish`. After having reinstalled stockfish, it now works, thank you.

**Comment by agausmann** [comment]
No problem! Glad it works

**Comment by philspence** [comment]
I'm also having the same problem. I have `stockfish` set up as an alias to the avx2 binary (have tried both stockfish 14 & 16 binaries). Running `./script.sh "$depth" "$fen" "$moves"` gives the expected outputs but `perftree ./script.sh` gives the same error as described above. Where am I going wrong? Thanks!

**Comment by agausmann** [comment]
Shell aliases won't work, as it doesn't execute the stockfish command through the user's shell. It looks for a program (or a symlink) named `stockfish` in the directories in your `PATH`.

I may consider adding a configuration option for the path to the stockfish binary.

**Comment by philspence** [comment]
Ah, that fixed it. Moved the binary to `/usr/bin` and symlinked to `/usr/bin/stockfish`. Thanks!
